# Generated by Django 3.1.7 on 2021-03-05 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210305_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='valid_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
